import 'dotenv/config';
import mongoose from 'mongoose';
import bcrypt from 'bcrypt';
import { config } from './src/config';
import { UserModel } from './src/modules/auth/infrastructure/models/User.model';
import { RoleModel } from './src/modules/auth/infrastructure/models/Role.model';
import { CompanyModel } from './src/modules/company/infrastructure/models/Company.model';
import { ServiceModel } from './src/modules/service/infrastructure/models/Service.model';

async function seed() {
  try {
    await mongoose.connect(config.MONGODB_URI);
    console.log('Connected to MongoDB for Seeding...');

    // 1. Create or Find Companies
    let skyfallCompany = await CompanyModel.findOne({ code: 'SKYFALL' });
    if (!skyfallCompany) {
      skyfallCompany = await CompanyModel.create({
        name: 'Skyfall International Travels',
        code: 'SKYFALL',
      });
    }

    let meridian = await CompanyModel.findOne({ code: 'FIN' });
    if (!meridian) {
      meridian = await CompanyModel.create({
        name: 'Meridian Capital',
        code: 'FIN',
      });
    }

    // 2. Create or Find Roles
    const superAdminRole = await RoleModel.findOneAndUpdate(
      { name: 'Super Admin' },
      {
        name: 'Super Admin',
        description: 'Full Global System Control',
        permissions: [
          'manage_users',
          'manage_workspaces',
          'view_all_finances',
          'approve_documents',
          'manage_settings',
          'manage_services',
          'view_services',
          'manage_travel',
          'view_travel',
          '*',
        ],
      },
      { upsert: true, returnDocument: 'after' },
    );

    const adminRole = await RoleModel.findOneAndUpdate(
      { name: 'Admin' },
      {
        name: 'Admin',
        description: 'Branch & Operations Control',
        permissions: [
          'view_travel',
          'manage_travel',
          'view_services',
          'manage_services',
          'generate_invoices',
          'view_customers',
          'manage_customers',
          'view_reports',
          'approve_documents',
          'create_proposals',
          'create_quotations',
        ],
      },
      { upsert: true, returnDocument: 'after' },
    );

    const employeeRole = await RoleModel.findOneAndUpdate(
      { name: 'Employee' },
      {
        name: 'Employee',
        description: 'Operations & Service Processing',
        permissions: [
          'view_travel',
          'view_services',
          'view_customers',
          'manage_assigned_customers',
          'draft_quotations',
          'view_bookings',
        ],
      },
      { upsert: true, returnDocument: 'after' },
    );

    // 3. Create or Update Default Users
    const defaultPassword = await bcrypt.hash('SecurePassword123!', 10);
    const legacyPassword = await bcrypt.hash('password123', 10);

    const usersToSeed = [
      {
        email: 'superadmin@skyfall.ae',
        name: 'ADMIN',
        role: 'super_admin' as const,
        isSuperAdmin: true,
        avatar_color: 'bg-purple-600',
        avatar_initials: 'CE',
        companyId: skyfallCompany._id,
        currentCompanyId: skyfallCompany._id,
        roleId: superAdminRole._id,
        passwordHash: defaultPassword,
      },
      {
        email: 'admin@skyfall.ae',
        name: 'ADMIN',
        role: 'admin' as const,
        isSuperAdmin: false,
        avatar_color: 'bg-blue-600',
        avatar_initials: 'SE',
        companyId: skyfallCompany._id,
        currentCompanyId: skyfallCompany._id,
        roleId: adminRole._id,
        passwordHash: defaultPassword,
      },
      {
        email: 'employee@skyfall.ae',
        name: 'EMPLOYEE',
        role: 'employee' as const,
        isSuperAdmin: false,
        avatar_color: 'bg-emerald-600',
        avatar_initials: 'HM',
        companyId: skyfallCompany._id,
        currentCompanyId: skyfallCompany._id,
        roleId: employeeRole._id,
        passwordHash: defaultPassword,
      },
      {
        email: 'superadmin@erp.com',
        name: 'GLOBAL SUPERADMIN',
        role: 'super_admin' as const,
        isSuperAdmin: true,
        avatar_color: 'bg-purple-600',
        avatar_initials: 'GS',
        companyId: skyfallCompany._id,
        currentCompanyId: skyfallCompany._id,
        roleId: superAdminRole._id,
        passwordHash: legacyPassword,
      },
    ];

    for (const u of usersToSeed) {
      await UserModel.findOneAndUpdate(
        { email: u.email },
        { ...u, status: 'active' },
        { upsert: true, returnDocument: 'after' },
      );
      console.log(`✓ User configured: ${u.email} [${u.role}]`);
    }

    // 4. Seed Skyfall Services Catalog
    const sampleServices = [
      {
        name: "Company Formation",
        category: "UAE Business Services",
        sub_category: "Business Formation & Licensing",
        description: "Establish a new corporate entity in the UAE mainland or free zones, including registration, drafting MOA, and company registry.",
        government_department: "DET / Freezone Authorities",
        country: "UAE",
        government_fee: 12000,
        company_service_charge: 4000,
        total_cost: 16000,
        currency: "AED",
        priority: "high" as const,
        status: "active" as const,
        approval_required: true,
        tags: ["business setup", "mainland", "freezone"]
      },
      {
        name: "Business Setup",
        category: "UAE Business Services",
        sub_category: "Business Formation & Licensing",
        description: "End-to-end consulting and logistical setup for new businesses in the UAE.",
        government_department: "DET",
        country: "UAE",
        government_fee: 5000,
        company_service_charge: 3000,
        total_cost: 8000,
        currency: "AED",
        priority: "normal" as const,
        status: "active" as const,
        approval_required: false,
        tags: ["business setup", "consulting"]
      },
      {
        name: "External Approvals",
        category: "UAE Business Services",
        sub_category: "Business Formation & Licensing",
        description: "Secure necessary approvals from third-party authorities such as Civil Defense, Municipality, SIRA, or RTA.",
        government_department: "Civil Defense / Dubai Municipality",
        country: "UAE",
        government_fee: 1500,
        company_service_charge: 1000,
        total_cost: 2500,
        currency: "AED",
        priority: "normal" as const,
        status: "active" as const,
        approval_required: true,
        tags: ["approvals", "government"]
      },
      {
        name: "Trade License (New)",
        category: "UAE Business Services",
        sub_category: "Business Formation & Licensing",
        description: "Issuance of new commercial, professional, or industrial trade licenses in Dubai and other emirates.",
        government_department: "DET",
        country: "UAE",
        government_fee: 10000,
        company_service_charge: 2500,
        total_cost: 12500,
        currency: "AED",
        priority: "high" as const,
        status: "active" as const,
        approval_required: true,
        tags: ["trade license", "licensing"]
      },
      {
        name: "Trade License Renewal",
        category: "UAE Business Services",
        sub_category: "Business Formation & Licensing",
        description: "Annual renewal of active trade licenses to ensure compliance and uninterrupted business operations.",
        government_department: "DET",
        country: "UAE",
        government_fee: 8000,
        company_service_charge: 1500,
        total_cost: 9500,
        currency: "AED",
        priority: "high" as const,
        status: "active" as const,
        approval_required: false,
        tags: ["trade license", "renewal"]
      },
      {
        name: "Ejari Registration",
        category: "UAE Business Services",
        sub_category: "Office & Compliance",
        description: "Attestation and registration of commercial or residential tenancy contracts with Dubai Land Department.",
        government_department: "DLD",
        country: "UAE",
        government_fee: 220,
        company_service_charge: 180,
        total_cost: 400,
        currency: "AED",
        priority: "normal" as const,
        status: "active" as const,
        approval_required: false,
        tags: ["ejari", "tenancy", "office"]
      },
      {
        name: "Istidama Services",
        category: "UAE Business Services",
        sub_category: "Office & Compliance",
        description: "Sustainability and green building compliance check and certificate issuance for Abu Dhabi properties.",
        government_department: "Abu Dhabi Municipality",
        country: "UAE",
        government_fee: 1200,
        company_service_charge: 800,
        total_cost: 2000,
        currency: "AED",
        priority: "normal" as const,
        status: "active" as const,
        approval_required: true,
        tags: ["istidama", "sustainability", "compliance"]
      },
      {
        name: "Office Space Solutions",
        category: "UAE Business Services",
        sub_category: "Office & Compliance",
        description: "Sourcing and setup of virtual, flexi-desk, or physical office space to meet licensing requirements.",
        government_department: "DLD / DET",
        country: "UAE",
        government_fee: 5000,
        company_service_charge: 2000,
        total_cost: 7000,
        currency: "AED",
        priority: "normal" as const,
        status: "active" as const,
        approval_required: false,
        tags: ["office space", "flexidesk", "rent"]
      },
      {
        name: "Property Lending Services",
        category: "UAE Business Services",
        sub_category: "Office & Compliance",
        description: "Assistance with commercial property leasing, financing, or property lending setups.",
        government_department: "Land Department / Banks",
        country: "UAE",
        government_fee: 1000,
        company_service_charge: 1500,
        total_cost: 2500,
        currency: "AED",
        priority: "low" as const,
        status: "active" as const,
        approval_required: true,
        tags: ["property lending", "leasing", "finance"]
      },
      {
        name: "PRO Services",
        category: "UAE Business Services",
        sub_category: "Government & PRO Services",
        description: "Public Relations Officer services for company documents, visa processing, and government departments.",
        government_department: "MOHRE / ICP",
        country: "UAE",
        government_fee: 0,
        company_service_charge: 1500,
        total_cost: 1500,
        currency: "AED",
        priority: "normal" as const,
        status: "active" as const,
        approval_required: false,
        tags: ["pro services", "government", "public relations"]
      },
      {
        name: "Amer Services",
        category: "UAE Business Services",
        sub_category: "Government & PRO Services",
        description: "Sponsorship and entry permit processing via government Amer centers in Dubai.",
        government_department: "GDRFA",
        country: "UAE",
        government_fee: 500,
        company_service_charge: 200,
        total_cost: 700,
        currency: "AED",
        priority: "high" as const,
        status: "active" as const,
        approval_required: false,
        tags: ["amer", "visa processing"]
      },
      {
        name: "Tasheel Services",
        category: "UAE Business Services",
        sub_category: "Government & PRO Services",
        description: "MOHRE labor transactions, work permits, and employment contract setups via Tasheel centers.",
        government_department: "MOHRE",
        country: "UAE",
        government_fee: 600,
        company_service_charge: 250,
        total_cost: 850,
        currency: "AED",
        priority: "high" as const,
        status: "active" as const,
        approval_required: false,
        tags: ["tasheel", "labor", "work permit"]
      },
      {
        name: "Golden Visa",
        category: "UAE Visa & Immigration Services",
        sub_category: "Residency & Long-Term Visas",
        description: "10-year residency visa processing for investors, professionals, entrepreneurs, and exceptional talents.",
        government_department: "GDRFA / ICP",
        country: "UAE",
        government_fee: 2800,
        company_service_charge: 3500,
        total_cost: 6300,
        currency: "AED",
        priority: "high" as const,
        status: "active" as const,
        approval_required: true,
        tags: ["golden visa", "residency", "investor"]
      },
      {
        name: "Employment Visa",
        category: "UAE Visa & Immigration Services",
        sub_category: "Residency & Long-Term Visas",
        description: "Standard 2-year residency visa processing for company employees, sponsored via MOHRE.",
        government_department: "MOHRE / ICP",
        country: "UAE",
        government_fee: 1500,
        company_service_charge: 1200,
        total_cost: 2700,
        currency: "AED",
        priority: "high" as const,
        status: "active" as const,
        approval_required: true,
        tags: ["employment visa", "residency", "work visa"]
      },
      {
        name: "Spouse Visa",
        category: "UAE Visa & Immigration Services",
        sub_category: "Residency & Long-Term Visas",
        description: "Family sponsorship visa processing to sponsor a husband or wife under resident sponsorship.",
        government_department: "GDRFA / ICP",
        country: "UAE",
        government_fee: 1200,
        company_service_charge: 800,
        total_cost: 2000,
        currency: "AED",
        priority: "normal" as const,
        status: "active" as const,
        approval_required: false,
        tags: ["spouse visa", "family sponsorship"]
      },
      {
        name: "UAE Visitor Visa (30 & 60 days)",
        category: "UAE Visa & Immigration Services",
        sub_category: "Entry Visas",
        description: "Tourist or business entry permits for visits of 30 or 60 days to the UAE.",
        government_department: "ICP / GDRFA",
        country: "UAE",
        government_fee: 450,
        company_service_charge: 150,
        total_cost: 600,
        currency: "AED",
        priority: "high" as const,
        status: "active" as const,
        approval_required: false,
        tags: ["visitor visa", "tourist visa", "entry permit"]
      },
      {
        name: "Worldwide Air Ticket Booking",
        category: "Travel & Tourism Services",
        sub_category: "Air Travel",
        description: "Global flight reservations and ticketing for all commercial airlines.",
        government_department: "IATA / Airlines",
        country: "Global",
        government_fee: 0,
        company_service_charge: 150,
        total_cost: 150,
        currency: "AED",
        priority: "normal" as const,
        status: "active" as const,
        approval_required: false,
        tags: ["air travel", "flight booking", "tickets"]
      },
      {
        name: "GCC Tourist Visa",
        category: "Travel & Tourism Services",
        sub_category: "Tourist Visas",
        description: "Tourist visa processing for GCC residents traveling to neighboring gulf countries.",
        government_department: "GCC Embassies",
        country: "GCC",
        government_fee: 300,
        company_service_charge: 150,
        total_cost: 450,
        currency: "AED",
        priority: "normal" as const,
        status: "active" as const,
        approval_required: false,
        tags: ["gcc visa", "tourist visa"]
      },
      {
        name: "Global Visa Assistance",
        category: "Travel & Tourism Services",
        sub_category: "Tourist Visas",
        description: "Document preparation, slot booking, and consultation for outbound tourist visas worldwide.",
        government_department: "VFS Global / Embassies",
        country: "Global",
        government_fee: 0,
        company_service_charge: 450,
        total_cost: 450,
        currency: "AED",
        priority: "normal" as const,
        status: "active" as const,
        approval_required: false,
        tags: ["visa assistance", "outbound visa"]
      },
      {
        name: "Holiday Packages (UAE, UK, KSA)",
        category: "Travel & Tourism Services",
        sub_category: "Holiday & Religious Travel",
        description: "Tailor-made vacation planning including flights, hotels, and sightseeing transfers in UAE, UK, or Saudi Arabia.",
        government_department: "Tourism Board",
        country: "Global",
        government_fee: 0,
        company_service_charge: 1000,
        total_cost: 1000,
        currency: "AED",
        priority: "normal" as const,
        status: "active" as const,
        approval_required: false,
        tags: ["holiday", "tour packages", "vacation"]
      },
      {
        name: "Umrah Services (from India & UAE)",
        category: "Travel & Tourism Services",
        sub_category: "Holiday & Religious Travel",
        description: "Complete Umrah packages including visa, flights, hotel reservations, and ground transport from India or UAE.",
        government_department: "Ministry of Hajj & Umrah",
        country: "KSA",
        government_fee: 600,
        company_service_charge: 800,
        total_cost: 1400,
        currency: "AED",
        priority: "high" as const,
        status: "active" as const,
        approval_required: true,
        tags: ["umrah", "pilgrimage", "saudi"]
      },
      {
        name: "Travel Insurance",
        category: "Travel & Tourism Services",
        sub_category: "Travel Support",
        description: "Comprehensive medical and travel insurance coverage for global trips.",
        government_department: "Insurance Companies",
        country: "Global",
        government_fee: 120,
        company_service_charge: 80,
        total_cost: 200,
        currency: "AED",
        priority: "low" as const,
        status: "active" as const,
        approval_required: false,
        tags: ["insurance", "travel support"]
      },
      {
        name: "Hotel Reservations",
        category: "Travel & Tourism Services",
        sub_category: "Travel Support",
        description: "Global hotel bookings from budget properties to luxury resorts.",
        government_department: "Hotels",
        country: "Global",
        government_fee: 0,
        company_service_charge: 200,
        total_cost: 200,
        currency: "AED",
        priority: "normal" as const,
        status: "active" as const,
        approval_required: false,
        tags: ["hotels", "reservations", "travel support"]
      },
      {
        name: "Passport Services (New, Renewal)",
        category: "Travel & Tourism Services",
        sub_category: "Travel Support",
        description: "Assistance with passport applications, renewals, or expat consular passport processing.",
        government_department: "Consulates / Embassies",
        country: "Global",
        government_fee: 300,
        company_service_charge: 250,
        total_cost: 550,
        currency: "AED",
        priority: "normal" as const,
        status: "active" as const,
        approval_required: false,
        tags: ["passport", "consular"]
      },
      {
        name: "Document Attestation",
        category: "Travel & Tourism Services",
        sub_category: "Travel Support",
        description: "Ministry attestation services for commercial, educational, or personal certificates.",
        government_department: "MOFA / Consulates",
        country: "UAE",
        government_fee: 150,
        company_service_charge: 200,
        total_cost: 350,
        currency: "AED",
        priority: "normal" as const,
        status: "active" as const,
        approval_required: false,
        tags: ["attestation", "mofa", "documents"]
      },
      {
        name: "Student Visa (Higher Studies)",
        category: "Europe Services",
        sub_category: "Visa Services",
        description: "Higher studies student visa consulting and processing support for European universities.",
        government_department: "European Embassies",
        country: "Europe",
        government_fee: 400,
        company_service_charge: 1200,
        total_cost: 1600,
        currency: "AED",
        priority: "high" as const,
        status: "active" as const,
        approval_required: true,
        tags: ["student visa", "higher education", "europe"]
      },
      {
        name: "UK Visit Visa (6 Months & 2 years)",
        category: "Europe Services",
        sub_category: "Visa Services",
        description: "Visit visa application processing for UK travel (6 months short term or 2 years long term).",
        government_department: "UKVI",
        country: "United Kingdom",
        government_fee: 600,
        company_service_charge: 500,
        total_cost: 1100,
        currency: "AED",
        priority: "high" as const,
        status: "active" as const,
        approval_required: true,
        tags: ["uk visa", "visit visa", "ukvi"]
      },
      {
        name: "Schengen Visa",
        category: "Europe Services",
        sub_category: "Visa Services",
        description: "Schengen travel visa assistance, documentation review, and appointment slot booking.",
        government_department: "Schengen Embassies",
        country: "Europe",
        government_fee: 350,
        company_service_charge: 450,
        total_cost: 800,
        currency: "AED",
        priority: "normal" as const,
        status: "active" as const,
        approval_required: true,
        tags: ["schengen visa", "europe", "tourist visa"]
      },
      {
        name: "Europe Travel Packages",
        category: "Europe Services",
        sub_category: "Travel & Relocation",
        description: "Custom tours and travel packages across key European destination cities.",
        government_department: "Hotels / Tour Operators",
        country: "Europe",
        government_fee: 0,
        company_service_charge: 1500,
        total_cost: 1500,
        currency: "AED",
        priority: "normal" as const,
        status: "active" as const,
        approval_required: false,
        tags: ["travel packages", "europe", "tour"]
      },
      {
        name: "Accommodation Services",
        category: "Europe Services",
        sub_category: "Travel & Relocation",
        description: "Sourcing short-term or long-term rental accommodation for expats and travelers in Europe.",
        government_department: "Agencies",
        country: "Europe",
        government_fee: 0,
        company_service_charge: 1000,
        total_cost: 1000,
        currency: "AED",
        priority: "normal" as const,
        status: "active" as const,
        approval_required: false,
        tags: ["accommodation", "rentals", "relocation"]
      },
      {
        name: "Property Lending Services (Europe)",
        category: "Europe Services",
        sub_category: "Travel & Relocation",
        description: "Assistance with commercial property leasing or property lending services for relocation.",
        government_department: "Lenders / Landlords",
        country: "Europe",
        government_fee: 500,
        company_service_charge: 1500,
        total_cost: 2000,
        currency: "AED",
        priority: "low" as const,
        status: "active" as const,
        approval_required: true,
        tags: ["property lending", "leasing", "relocation"]
      },
      {
        name: "Travel Guidance",
        category: "Europe Services",
        sub_category: "Travel & Relocation",
        description: "Itinerary planning, rail cards, transit guides, and local travel advice for Europe.",
        government_department: "Tour Experts",
        country: "Europe",
        government_fee: 0,
        company_service_charge: 300,
        total_cost: 300,
        currency: "AED",
        priority: "low" as const,
        status: "active" as const,
        approval_required: false,
        tags: ["guidance", "travel support"]
      },
      {
        name: "Airport Pick-up & Drop-off",
        category: "Europe Services",
        sub_category: "Travel & Relocation",
        description: "Private chauffeured airport transfers in major European transit hubs.",
        government_department: "Transport Operators",
        country: "Europe",
        government_fee: 0,
        company_service_charge: 250,
        total_cost: 250,
        currency: "AED",
        priority: "normal" as const,
        status: "active" as const,
        approval_required: false,
        tags: ["airport transfer", "taxi"]
      },
      {
        name: "Money Transfer Assistance",
        category: "Europe Services",
        sub_category: "Travel & Relocation",
        description: "Consultation and facilitation of large cross-border currency transfers and bank account setups.",
        government_department: "Banks / FX Brokers",
        country: "Europe",
        government_fee: 0,
        company_service_charge: 500,
        total_cost: 500,
        currency: "AED",
        priority: "normal" as const,
        status: "active" as const,
        approval_required: false,
        tags: ["money transfer", "forex", "bank account"]
      },
      {
        name: "University Selection Assistance",
        category: "Study Abroad Services",
        sub_category: "University Admissions",
        description: "University selection assistance and consulting for study abroad.",
        government_department: "Admissions Office",
        country: "Global",
        government_fee: 0,
        company_service_charge: 800,
        total_cost: 800,
        currency: "AED",
        priority: "normal" as const,
        status: "active" as const,
        approval_required: false,
        tags: ["study abroad", "university selection"]
      },
      {
        name: "Admission Assistance",
        category: "Study Abroad Services",
        sub_category: "University Admissions",
        description: "Assistance with obtaining admission offers and letters of acceptance from foreign universities.",
        government_department: "Admissions Office",
        country: "Global",
        government_fee: 0,
        company_service_charge: 1000,
        total_cost: 1000,
        currency: "AED",
        priority: "normal" as const,
        status: "active" as const,
        approval_required: false,
        tags: ["study abroad", "admission"]
      },
      {
        name: "Course Selection",
        category: "Study Abroad Services",
        sub_category: "University Admissions",
        description: "Detailed course evaluation and match selection based on student background.",
        government_department: "Admissions Office",
        country: "Global",
        government_fee: 0,
        company_service_charge: 500,
        total_cost: 500,
        currency: "AED",
        priority: "normal" as const,
        status: "active" as const,
        approval_required: false,
        tags: ["course selection", "study abroad"]
      },
      {
        name: "Student Visa Processing",
        category: "Study Abroad Services",
        sub_category: "Student Visa Support",
        description: "End-to-end student visa application processing and consulate support.",
        government_department: "Embassies",
        country: "Global",
        government_fee: 600,
        company_service_charge: 1200,
        total_cost: 1800,
        currency: "AED",
        priority: "high" as const,
        status: "active" as const,
        approval_required: true,
        tags: ["student visa", "visa processing"]
      },
      {
        name: "Visa Documentation",
        category: "Study Abroad Services",
        sub_category: "Student Visa Support",
        description: "Guidance and verification of financial documentation and visa support files.",
        government_department: "Consulates",
        country: "Global",
        government_fee: 0,
        company_service_charge: 500,
        total_cost: 500,
        currency: "AED",
        priority: "normal" as const,
        status: "active" as const,
        approval_required: false,
        tags: ["visa documents", "documentation"]
      },
      {
        name: "Error documents clearing",
        category: "Study Abroad Services",
        sub_category: "Student Visa Support",
        description: "Specialized review and correction of document errors to clear visa or admission blocks.",
        government_department: "Consulates",
        country: "Global",
        government_fee: 200,
        company_service_charge: 800,
        total_cost: 1000,
        currency: "AED",
        priority: "normal" as const,
        status: "active" as const,
        approval_required: true,
        tags: ["error clearing", "documentation"]
      },
      {
        name: "Application Preparation",
        category: "Study Abroad Services",
        sub_category: "Application Assistance",
        description: "Help with statement of purpose (SOP), recommendation letters, and resume formatting.",
        government_department: "Admissions Office",
        country: "Global",
        government_fee: 0,
        company_service_charge: 600,
        total_cost: 600,
        currency: "AED",
        priority: "normal" as const,
        status: "active" as const,
        approval_required: false,
        tags: ["application prep", "sop"]
      },
      {
        name: "Documentation Support",
        category: "Study Abroad Services",
        sub_category: "Application Assistance",
        description: "Academic credential verification and translation coordination.",
        government_department: "Admissions Office",
        country: "Global",
        government_fee: 0,
        company_service_charge: 400,
        total_cost: 400,
        currency: "AED",
        priority: "normal" as const,
        status: "active" as const,
        approval_required: false,
        tags: ["documents", "academic credentials"]
      },
      {
        name: "Scholarship Assistance",
        category: "Study Abroad Services",
        sub_category: "Financial Guidance",
        description: "Identifying available scholarships, grants, and bursaries and assisting with applications.",
        government_department: "Scholarship Committee",
        country: "Global",
        government_fee: 0,
        company_service_charge: 800,
        total_cost: 800,
        currency: "AED",
        priority: "normal" as const,
        status: "active" as const,
        approval_required: false,
        tags: ["scholarship", "financial aid"]
      },
      {
        name: "Funding Guidance",
        category: "Study Abroad Services",
        sub_category: "Financial Guidance",
        description: "Expert advice on securing student loans, block accounts, and financial proof of funds.",
        government_department: "Banks / Financial Advisor",
        country: "Global",
        government_fee: 0,
        company_service_charge: 500,
        total_cost: 500,
        currency: "AED",
        priority: "normal" as const,
        status: "active" as const,
        approval_required: false,
        tags: ["funding", "student loan"]
      },
      {
        name: "Accommodation Assistance",
        category: "Study Abroad Services",
        sub_category: "Student Support",
        description: "Sourcing student housing, dormitories, or shared flats close to university campuses.",
        government_department: "Student Support",
        country: "Global",
        government_fee: 0,
        company_service_charge: 600,
        total_cost: 600,
        currency: "AED",
        priority: "normal" as const,
        status: "active" as const,
        approval_required: false,
        tags: ["accommodation", "student housing"]
      },
      {
        name: "Pre-Departure Briefing & Support",
        category: "Study Abroad Services",
        sub_category: "Student Support",
        description: "Briefing sessions on arrival procedures, health insurance, local transit, and cultural adjustments.",
        government_department: "Student Support",
        country: "Global",
        government_fee: 0,
        company_service_charge: 300,
        total_cost: 300,
        currency: "AED",
        priority: "low" as const,
        status: "active" as const,
        approval_required: false,
        tags: ["pre-departure", "briefing", "arrival support"]
      },
      {
        name: "Austria",
        category: "Study Abroad Services",
        sub_category: "Countries We Cover — Europe",
        description: "Study abroad guidance and university admissions in Austria.",
        government_department: "Study Abroad Admissions",
        country: "Austria",
        government_fee: 0,
        company_service_charge: 500,
        total_cost: 500,
        currency: "AED",
        priority: "normal" as const,
        status: "active" as const,
        approval_required: false,
        tags: ["study abroad", "austria", "europe"]
      },
      {
        name: "France",
        category: "Study Abroad Services",
        sub_category: "Countries We Cover — Europe",
        description: "Study abroad guidance and university admissions in France.",
        government_department: "Study Abroad Admissions",
        country: "France",
        government_fee: 0,
        company_service_charge: 500,
        total_cost: 500,
        currency: "AED",
        priority: "normal" as const,
        status: "active" as const,
        approval_required: false,
        tags: ["study abroad", "france", "europe"]
      },
      {
        name: "Germany",
        category: "Study Abroad Services",
        sub_category: "Countries We Cover — Europe",
        description: "Study abroad guidance and university admissions in Germany.",
        government_department: "Study Abroad Admissions",
        country: "Germany",
        government_fee: 0,
        company_service_charge: 500,
        total_cost: 500,
        currency: "AED",
        priority: "normal" as const,
        status: "active" as const,
        approval_required: false,
        tags: ["study abroad", "germany", "europe"]
      },
      {
        name: "Greece",
        category: "Study Abroad Services",
        sub_category: "Countries We Cover — Europe",
        description: "Study abroad guidance and university admissions in Greece.",
        government_department: "Study Abroad Admissions",
        country: "Greece",
        government_fee: 0,
        company_service_charge: 500,
        total_cost: 500,
        currency: "AED",
        priority: "normal" as const,
        status: "active" as const,
        approval_required: false,
        tags: ["study abroad", "greece", "europe"]
      },
      {
        name: "Ireland",
        category: "Study Abroad Services",
        sub_category: "Countries We Cover — Europe",
        description: "Study abroad guidance and university admissions in Ireland.",
        government_department: "Study Abroad Admissions",
        country: "Ireland",
        government_fee: 0,
        company_service_charge: 500,
        total_cost: 500,
        currency: "AED",
        priority: "normal" as const,
        status: "active" as const,
        approval_required: false,
        tags: ["study abroad", "ireland", "europe"]
      },
      {
        name: "Italy",
        category: "Study Abroad Services",
        sub_category: "Countries We Cover — Europe",
        description: "Study abroad guidance and university admissions in Italy.",
        government_department: "Study Abroad Admissions",
        country: "Italy",
        government_fee: 0,
        company_service_charge: 500,
        total_cost: 500,
        currency: "AED",
        priority: "normal" as const,
        status: "active" as const,
        approval_required: false,
        tags: ["study abroad", "italy", "europe"]
      },
      {
        name: "Latvia",
        category: "Study Abroad Services",
        sub_category: "Countries We Cover — Europe",
        description: "Study abroad guidance and university admissions in Latvia.",
        government_department: "Study Abroad Admissions",
        country: "Latvia",
        government_fee: 0,
        company_service_charge: 500,
        total_cost: 500,
        currency: "AED",
        priority: "normal" as const,
        status: "active" as const,
        approval_required: false,
        tags: ["study abroad", "latvia", "europe"]
      },
      {
        name: "Lithuania",
        category: "Study Abroad Services",
        sub_category: "Countries We Cover — Europe",
        description: "Study abroad guidance and university admissions in Lithuania.",
        government_department: "Study Abroad Admissions",
        country: "Lithuania",
        government_fee: 0,
        company_service_charge: 500,
        total_cost: 500,
        currency: "AED",
        priority: "normal" as const,
        status: "active" as const,
        approval_required: false,
        tags: ["study abroad", "lithuania", "europe"]
      },
      {
        name: "Malta",
        category: "Study Abroad Services",
        sub_category: "Countries We Cover — Europe",
        description: "Study abroad guidance and university admissions in Malta.",
        government_department: "Study Abroad Admissions",
        country: "Malta",
        government_fee: 0,
        company_service_charge: 500,
        total_cost: 500,
        currency: "AED",
        priority: "normal" as const,
        status: "active" as const,
        approval_required: false,
        tags: ["study abroad", "malta", "europe"]
      },
      {
        name: "Slovakia",
        category: "Study Abroad Services",
        sub_category: "Countries We Cover — Europe",
        description: "Study abroad guidance and university admissions in Slovakia.",
        government_department: "Study Abroad Admissions",
        country: "Slovakia",
        government_fee: 0,
        company_service_charge: 500,
        total_cost: 500,
        currency: "AED",
        priority: "normal" as const,
        status: "active" as const,
        approval_required: false,
        tags: ["study abroad", "slovakia", "europe"]
      },
      {
        name: "Spain",
        category: "Study Abroad Services",
        sub_category: "Countries We Cover — Europe",
        description: "Study abroad guidance and university admissions in Spain.",
        government_department: "Study Abroad Admissions",
        country: "Spain",
        government_fee: 0,
        company_service_charge: 500,
        total_cost: 500,
        currency: "AED",
        priority: "normal" as const,
        status: "active" as const,
        approval_required: false,
        tags: ["study abroad", "spain", "europe"]
      },
      {
        name: "Turkey",
        category: "Study Abroad Services",
        sub_category: "Countries We Cover — Europe",
        description: "Study abroad guidance and university admissions in Turkey.",
        government_department: "Study Abroad Admissions",
        country: "Turkey",
        government_fee: 0,
        company_service_charge: 500,
        total_cost: 500,
        currency: "AED",
        priority: "normal" as const,
        status: "active" as const,
        approval_required: false,
        tags: ["study abroad", "turkey", "europe"]
      },
      {
        name: "United Kingdom",
        category: "Study Abroad Services",
        sub_category: "Countries We Cover — Europe",
        description: "Study abroad guidance and university admissions in the United Kingdom.",
        government_department: "Study Abroad Admissions",
        country: "United Kingdom",
        government_fee: 0,
        company_service_charge: 500,
        total_cost: 500,
        currency: "AED",
        priority: "normal" as const,
        status: "active" as const,
        approval_required: false,
        tags: ["study abroad", "uk", "europe"]
      },
      {
        name: "Canada",
        category: "Study Abroad Services",
        sub_category: "Countries We Cover — North America",
        description: "Study abroad guidance and university admissions in Canada.",
        government_department: "Study Abroad Admissions",
        country: "Canada",
        government_fee: 0,
        company_service_charge: 500,
        total_cost: 500,
        currency: "AED",
        priority: "normal" as const,
        status: "active" as const,
        approval_required: false,
        tags: ["study abroad", "canada", "north america"]
      },
      {
        name: "United States",
        category: "Study Abroad Services",
        sub_category: "Countries We Cover — North America",
        description: "Study abroad guidance and university admissions in the United States.",
        government_department: "Study Abroad Admissions",
        country: "United States",
        government_fee: 0,
        company_service_charge: 500,
        total_cost: 500,
        currency: "AED",
        priority: "normal" as const,
        status: "active" as const,
        approval_required: false,
        tags: ["study abroad", "usa", "north america"]
      },
      {
        name: "Japan",
        category: "Study Abroad Services",
        sub_category: "Countries We Cover — Asia",
        description: "Study abroad guidance and university admissions in Japan.",
        government_department: "Study Abroad Admissions",
        country: "Japan",
        government_fee: 0,
        company_service_charge: 500,
        total_cost: 500,
        currency: "AED",
        priority: "normal" as const,
        status: "active" as const,
        approval_required: false,
        tags: ["study abroad", "japan", "asia"]
      },
      {
        name: "Malaysia",
        category: "Study Abroad Services",
        sub_category: "Countries We Cover — Asia",
        description: "Study abroad guidance and university admissions in Malaysia.",
        government_department: "Study Abroad Admissions",
        country: "Malaysia",
        government_fee: 0,
        company_service_charge: 500,
        total_cost: 500,
        currency: "AED",
        priority: "normal" as const,
        status: "active" as const,
        approval_required: false,
        tags: ["study abroad", "malaysia", "asia"]
      },
      {
        name: "Singapore",
        category: "Study Abroad Services",
        sub_category: "Countries We Cover — Asia",
        description: "Study abroad guidance and university admissions in Singapore.",
        government_department: "Study Abroad Admissions",
        country: "Singapore",
        government_fee: 0,
        company_service_charge: 500,
        total_cost: 500,
        currency: "AED",
        priority: "normal" as const,
        status: "active" as const,
        approval_required: false,
        tags: ["study abroad", "singapore", "asia"]
      },
      {
        name: "United Arab Emirates",
        category: "Study Abroad Services",
        sub_category: "Countries We Cover — Asia",
        description: "Study abroad guidance and university admissions in the United Arab Emirates.",
        government_department: "Study Abroad Admissions",
        country: "UAE",
        government_fee: 0,
        company_service_charge: 500,
        total_cost: 500,
        currency: "AED",
        priority: "normal" as const,
        status: "active" as const,
        approval_required: false,
        tags: ["study abroad", "uae", "asia"]
      },
      {
        name: "Australia",
        category: "Study Abroad Services",
        sub_category: "Countries We Cover — Oceania",
        description: "Study abroad guidance and university admissions in Australia.",
        government_department: "Study Abroad Admissions",
        country: "Australia",
        government_fee: 0,
        company_service_charge: 500,
        total_cost: 500,
        currency: "AED",
        priority: "normal" as const,
        status: "active" as const,
        approval_required: false,
        tags: ["study abroad", "australia", "oceania"]
      },
      {
        name: "New Zealand",
        category: "Study Abroad Services",
        sub_category: "Countries We Cover — Oceania",
        description: "Study abroad guidance and university admissions in New Zealand.",
        government_department: "Study Abroad Admissions",
        country: "New Zealand",
        government_fee: 0,
        company_service_charge: 500,
        total_cost: 500,
        currency: "AED",
        priority: "normal" as const,
        status: "active" as const,
        approval_required: false,
        tags: ["study abroad", "new zealand", "oceania"]
      },
      {
        name: "Foundation",
        category: "Study Abroad Services",
        sub_category: "Programs Available — Pathway Programs",
        description: "Admissions guidance for Foundation pathway courses.",
        government_department: "Admissions Department",
        country: "Global",
        government_fee: 0,
        company_service_charge: 1000,
        total_cost: 1000,
        currency: "AED",
        priority: "normal" as const,
        status: "active" as const,
        approval_required: false,
        tags: ["pathway", "foundation", "study abroad"]
      },
      {
        name: "International Year One",
        category: "Study Abroad Services",
        sub_category: "Programs Available — Pathway Programs",
        description: "Admissions guidance for International Year One programs.",
        government_department: "Admissions Department",
        country: "Global",
        government_fee: 0,
        company_service_charge: 1000,
        total_cost: 1000,
        currency: "AED",
        priority: "normal" as const,
        status: "active" as const,
        approval_required: false,
        tags: ["pathway", "international year one", "study abroad"]
      },
      {
        name: "Pre-Sessional Course",
        category: "Study Abroad Services",
        sub_category: "Programs Available — Pathway Programs",
        description: "Admissions guidance for Pre-Sessional english or preparation courses.",
        government_department: "Admissions Department",
        country: "Global",
        government_fee: 0,
        company_service_charge: 1000,
        total_cost: 1000,
        currency: "AED",
        priority: "normal" as const,
        status: "active" as const,
        approval_required: false,
        tags: ["pathway", "pre-sessional", "study abroad"]
      },
      {
        name: "Pre-Master's",
        category: "Study Abroad Services",
        sub_category: "Programs Available — Pathway Programs",
        description: "Admissions guidance for Pre-Master's pathway programs.",
        government_department: "Admissions Department",
        country: "Global",
        government_fee: 0,
        company_service_charge: 1000,
        total_cost: 1000,
        currency: "AED",
        priority: "normal" as const,
        status: "active" as const,
        approval_required: false,
        tags: ["pathway", "pre-master", "study abroad"]
      },
      {
        name: "Bachelor's Degree",
        category: "Study Abroad Services",
        sub_category: "Programs Available — Undergraduate Programs",
        description: "Admissions guidance for standard Bachelor's degree programs.",
        government_department: "Admissions Department",
        country: "Global",
        government_fee: 0,
        company_service_charge: 1000,
        total_cost: 1000,
        currency: "AED",
        priority: "normal" as const,
        status: "active" as const,
        approval_required: false,
        tags: ["undergraduate", "bachelors", "degree"]
      },
      {
        name: "Undergraduate (Year 2 Entry)",
        category: "Study Abroad Services",
        sub_category: "Programs Available — Undergraduate Programs",
        description: "Admissions guidance for direct entry into year 2 of undergraduate study.",
        government_department: "Admissions Department",
        country: "Global",
        government_fee: 0,
        company_service_charge: 1000,
        total_cost: 1000,
        currency: "AED",
        priority: "normal" as const,
        status: "active" as const,
        approval_required: false,
        tags: ["undergraduate", "year 2 entry", "degree"]
      },
      {
        name: "Undergraduate (Final Year Entry)",
        category: "Study Abroad Services",
        sub_category: "Programs Available — Undergraduate Programs",
        description: "Admissions guidance for direct entry into final year of undergraduate study.",
        government_department: "Admissions Department",
        country: "Global",
        government_fee: 0,
        company_service_charge: 1000,
        total_cost: 1000,
        currency: "AED",
        priority: "normal" as const,
        status: "active" as const,
        approval_required: false,
        tags: ["undergraduate", "final year", "degree"]
      },
      {
        name: "Undergraduate Top-Up",
        category: "Study Abroad Services",
        sub_category: "Programs Available — Undergraduate Programs",
        description: "Admissions guidance for Top-Up programs to convert diploma into Bachelor's degree.",
        government_department: "Admissions Department",
        country: "Global",
        government_fee: 0,
        company_service_charge: 1000,
        total_cost: 1000,
        currency: "AED",
        priority: "normal" as const,
        status: "active" as const,
        approval_required: false,
        tags: ["undergraduate", "top-up", "degree"]
      },
      {
        name: "Postgraduate",
        category: "Study Abroad Services",
        sub_category: "Programs Available — Postgraduate Programs",
        description: "Admissions guidance for Postgraduate certificates or diplomas.",
        government_department: "Admissions Department",
        country: "Global",
        government_fee: 0,
        company_service_charge: 1000,
        total_cost: 1000,
        currency: "AED",
        priority: "normal" as const,
        status: "active" as const,
        approval_required: false,
        tags: ["postgraduate", "diploma"]
      },
      {
        name: "Master's Degree",
        category: "Study Abroad Services",
        sub_category: "Programs Available — Postgraduate Programs",
        description: "Admissions guidance for taught Master's degree programs.",
        government_department: "Admissions Department",
        country: "Global",
        government_fee: 0,
        company_service_charge: 1000,
        total_cost: 1000,
        currency: "AED",
        priority: "normal" as const,
        status: "active" as const,
        approval_required: false,
        tags: ["postgraduate", "masters", "degree"]
      },
      {
        name: "Master of Research (MRes)",
        category: "Study Abroad Services",
        sub_category: "Programs Available — Postgraduate Programs",
        description: "Admissions guidance for Master of Research (MRes) programs.",
        government_department: "Admissions Department",
        country: "Global",
        government_fee: 0,
        company_service_charge: 1000,
        total_cost: 1000,
        currency: "AED",
        priority: "normal" as const,
        status: "active" as const,
        approval_required: false,
        tags: ["postgraduate", "mres", "research"]
      },
      {
        name: "PhD",
        category: "Study Abroad Services",
        sub_category: "Programs Available — Postgraduate Programs",
        description: "Admissions guidance for Doctoral / PhD research programs.",
        government_department: "Admissions Department",
        country: "Global",
        government_fee: 0,
        company_service_charge: 1000,
        total_cost: 1000,
        currency: "AED",
        priority: "normal" as const,
        status: "active" as const,
        approval_required: true,
        tags: ["phd", "doctorate", "research"]
      }
    ];

    for (const s of sampleServices) {
      await ServiceModel.findOneAndUpdate(
        { name: s.name, category: s.category },
        { ...s, serviceName: s.name, companyId: skyfallCompany._id },
        { upsert: true, returnDocument: 'after' },
      );
      console.log(`✓ Service catalog entry configured: ${s.name} [${s.category}]`);
    }

    console.log('\n=============================================');
    console.log('✅ SKYFALL INTERNATIONAL TRAVELS SEED COMPLETE');
    console.log('=============================================');
    console.log('Default Accounts:');
    console.log('1. Super Admin: superadmin@skyfall.ae / SecurePassword123!');
    console.log('2. Admin:       admin@skyfall.ae       / SecurePassword123!');
    console.log('3. Employee:    employee@skyfall.ae    / SecurePassword123!');
    console.log('4. Legacy:      superadmin@erp.com     / password123');
    console.log('=============================================\n');

    process.exit(0);
  } catch (err) {
    console.error('Seeding error:', err);
    process.exit(1);
  }
}

seed();

